food/food/urls.py
from django.contrib import admin
from django.urls import path,include
from users import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls'))
    ,
    path('register/',user_views.register,name='register'),
    path('login/',authentication_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',authentication_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('profile/',user_views.profilepage,name='profile')

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

food/myapp/urls.py
from django.urls import path
from . import views
app_name='myapp'
urlpatterns = [
    
    path('',views.index,name='index'),
    path('<int:item_id>/',views.detail,name="detail"),
    # add item
    path('add/',views.create_item,name="create_item"),
    # edit
    path('update/<int:id>/',views.update_item,name='update_item'),
    path('delete/<int:id>/',views.delete_item,name="delete_item"),
]

food/myapp/models.py
from django.db import models

# Create your models here.
class Item(models.Model):
    item_name=models.CharField(max_length=200)
    item_desc=models.CharField(max_length=200)
    item_price=models.IntegerField()
    item_image=models.CharField(max_length=1000)
    def __str__(self):
        return self.item_name

food/users/models.py
from django.db import models
from django.contrib.auth.models import User 
# Create your models here.

class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    image=models.ImageField(default='profilepic.jpg',upload_to='profile_pictures')
    location =models.CharField(max_length=100)


    def __str__(self):
        return self.user.username

food/myapp/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name','item_desc','item_price','item_image']
        

food/users/forms.py
from socket import fromshare
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email= forms.EmailField()

    class Meta:
        model=User
        fields=['username','email','password1','password2']

food/myapp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .forms import ItemForm

from . models import Item
# Create your views here.
def index(request):
    item_list=Item.objects.all()
    context={
        'item_list':item_list
    }
    return render(request,'food/index.html',context)

def detail(request,item_id):
    item=Item.objects.get(pk=item_id)
    context={
        'item':item
    }
    return render(request,'food/detail.html',context)

def create_item(request):
    form=ItemForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('myapp:index')
    return render(request,'food/item-form.html',{'form':form})
    
def update_item(request,id):
    item=Item.objects.get(id=id)
    form =ItemForm(request.POST or None , instance=item)
    if form.is_valid():
        form.save()
        return redirect('myapp:index')
    
    return render(request,'food/item-form.html',{'form':form,'item':item})

def delete_item(request,id):
    item=Item.objects.get(id=id)

    if(request.method=='POST'):
        item.delete()
        return redirect('myapp:index')
    return render(request,'food/item-delete.html',{'item':item})

food/users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import RegisterForm
from django.contrib.auth.decorators import login_required
# Create your views here.

def register(request):
    if request.method == 'POST':
        form=RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username=form.cleaned_data.get('username')
            messages.success(request,f'Welcome {username},your account is created')
            return redirect('login')
    else:
        form=RegisterForm()
    return render(request,'users/register.html',{'form':form})

@login_required
def profilepage(request):
    return render(request,'users/profile.html')

food/myapp/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-dark" style="margin-bottom:20px;">
        <div class="container-fluid">
          <a class="navbar-brand text-white" href="#">FoodApp</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
               
                <a class="nav-link text-white" aria-current="page" href="{% url 'myapp:create_item' %}">Add Item</a>
                
              </li>
            
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link text-white" aria-current="page" href="{% url 'profile' %}">Profile</a>
              </li>
             {% endif %}
             
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
            {% if user.is_authenticated %}
            <a href="{% url 'logout' %}" class="btn btn-outline-success">Logout</a>
            {% else %}
            <a href="{% url 'login' %}" class="btn btn-outline-success">Login</a>
            {% endif %}
          </div>
        </div>
      </nav>
{% if messages %}
{% for message in  messages %}

<div class="alert alert-{{message.tags}}">
  {{message}}
</div>
{% endfor %}
{% endif %}
      
   {% block content %}

   {% endblock %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

food/myapp/templates/food/detail.html
{% extends 'food/base.html' %}

{% block content %}
<div class="card mb-3 offset-md-3" style="max-width: 600px;">
    <div class="row g-0">
      <div class="col-md-3 d-flex align-items-center">
        <img src="{{item.item_image}}" style="max-width:100%; max-height: 100%; " class="img-fluid rounded-start" alt="...">
      </div>
      <div class="col-md-7">
        <div class="card-body">
          <h5 class="card-title">{{item.item_name}}</h5>
          <p class="card-text">{{item.item_desc}}</p>
          <p class="card-text">${{item.item_price}}</p>
        </div>
      </div>
      <div class="col-md-2 text-center d-flex align-items-center ">
        <a href="{% url 'myapp:delete_item' item.id %}"  class="btn btn-success">delete</a>
      </div>
    </div>
  </div>
{% endblock %}

food/myapp/templates/food/index.html
{% extends 'food/base.html' %}
{% block content %}

{% for item in item_list %}

<div class="card mb-3 offset-md-3" style="max-width: 600px;">
    <div class="row g-0">
      <div class="col-md-3 d-flex align-items-center">
        <img src="{{item.item_image}}" style="max-width:100%; max-height: 100%; " class="img-fluid rounded-start" alt="...">
      </div>
      <div class="col-md-7">
        <div class="card-body">
          <h5 class="card-title">{{item.item_name}}</h5>
          <p class="card-text">{{item.item_desc}}</p>
          <p class="card-text">${{item.item_price}}</p>
        </div>
      </div>
      <div class="col-md-2 text-center d-flex align-items-center ">
        <a href="{% url 'myapp:detail' item.id %}"  class="btn btn-success">Detail</a>
      </div>
    </div>
  </div>
  {% endfor %}
{% endblock %}

food/myapp/templates/food/item-delete.html
<form action="" method="POST">
    {% csrf_token %}
    <h2>Are you sure want to delete {{item.item_name}}</h2>
    <button type="submit">Confirm</button>
</form>

food/myapp/templates/food/item-form.html
{% extends 'food/base.html' %}

{% block content %}

<div class="container my-4">
 <div class="col-md-4 offset-md-4">
    <div class="card">
        <div class="card-header text-white bg-info">
            <div class="card-title">
              Item Add
            </div>
        </div>
        <div class="card-body">
            <form action="" method="POST">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group">
                    <div class="my-1">{{field.name}}</div>
                    <div class="my-1">{{field}}</div>
                </div>
                {% endfor %}
                <button type="submit" class="btn btn-info my-1">Save</button>
            </form>
        </div>
    </div>
 </div>
</div>
{% endblock %}

food/users/templates/users/login.html
{% extends 'food/base.html' %}

{% block content %}

<div class="container my-4">
 <div class="col-md-4 offset-md-4">
    <div class="card">
        <div class="card-header text-white bg-info">
            <div class="card-title">
                Login
            </div>
        </div>
        <div class="card-body">
            <form action="" method="POST">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group">
                    <div class="my-1">{{field.name}}</div>
                    <div class="my-1">{{field}}</div>
                </div>
                {% endfor %}
                <button type="submit" class="btn btn-info my-1">Login</button>
                <div><a href="{% url 'register' %}">Register Here</a></div>
            </form>
        </div>
    </div>
 </div>
</div>
{% endblock %}

food/users/templates/users/logout.html
<h1>You have been logout</h1>

food/users/templates/users/profile.html
<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
.card {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  max-width: 300px;
  margin: auto;
  text-align: center;
  font-family: arial;
}

.title {
  color: grey;
  font-size: 18px;
}

button {
  border: none;
  outline: 0;
  display: inline-block;
  padding: 8px;
  color: white;
  background-color: #000;
  text-align: center;
  cursor: pointer;
  width: 100%;
  font-size: 18px;
}

a {
  text-decoration: none;
  font-size: 22px;
  color: black;
}

button:hover, a:hover {
  opacity: 0.7;
}
</style>
</head>
<body>

<h2 style="text-align:center">User Profile Card</h2>

<div class="card">
  <img src="{{user.profile.image.url}}" alt="John" style="width:100%">
  <h1>{{user.username}}</h1>
  <p class="title">{{user.email}}</p>
  
  <div style="margin: 24px 0;">
    <a href="#"><i class="fa fa-dribbble"></i></a> 
    <a href="#"><i class="fa fa-twitter"></i></a>  
    <a href="#"><i class="fa fa-linkedin"></i></a>  
    <a href="#"><i class="fa fa-facebook"></i></a> 
  </div>
  <p><button>Contact</button></p>
</div>

</body>
</html>

food/users/templates/users/register.html
{% extends 'food/base.html' %}

{% block content %}

<div class="container my-4">
 <div class="col-md-4 offset-md-4">
    <div class="card">
        <div class="card-header text-white bg-info">
            <div class="card-title">
               Register
            </div>
        </div>
        <div class="card-body">
            <form action="" method="POST">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group">
                    <div class="my-1">{{field.name}}</div>
                    <div class="my-1">{{field}}</div>
                </div>
                {% endfor %}
                <button type="submit" class="btn btn-info my-1">Signup</button>
            </form>
        </div>
    </div>
 </div>
</div>
{% endblock %}

























<form action="" method="POST">
    {% csrf_token %}
    {{form}}
    <button type="submit">Signup</button>
</form>